In [52]:
import numpy as np
from sklearn.preprocessing import StandardScaler

file=open(r'Fish_PCA.csv')
docs=file.read().split('\n')
docs=docs[1:-1]
ds=list()
for i in docs:
  t=list()
  temp=i.split(',')
  for j in temp:
    try:
      t.append(eval(j))
    except:
      continue
  ds.append(t)
ds=np.array(ds)

In [53]:
dataset=ds[0:10,0:3]
print(dataset)

[[242.   23.2  25.4]
 [290.   24.   26.3]
 [340.   23.9  26.5]
 [363.   26.3  29. ]
 [430.   26.5  29. ]
 [450.   26.8  29.7]
 [500.   26.8  29.7]
 [390.   27.6  30. ]
 [450.   27.6  30. ]
 [500.   28.5  30.7]]


In [54]:
#mean centricity
scaler=StandardScaler()
dataset=scaler.fit_transform(dataset)
print(dataset)

[[-1.86378525 -1.71185197 -1.83448714]
 [-1.28097292 -1.24285143 -1.32332973]
 [-0.67387675 -1.3014765  -1.2097392 ]
 [-0.39461251  0.10552512  0.21014249]
 [ 0.41889636  0.22277526  0.21014249]
 [ 0.66173483  0.39865046  0.60770936]
 [ 1.268831    0.39865046  0.60770936]
 [-0.06678058  0.867651    0.77809516]
 [ 0.66173483  0.867651    0.77809516]
 [ 1.268831    1.39527661  1.17566203]]


In [55]:
#covariance matrix
cov_mat=np.cov([dataset[:,0],dataset[:,1],dataset[:,2]])
print(cov_mat)

[[1.11111111 0.9741667  1.00693647]
 [0.9741667  1.11111111 1.10040452]
 [1.00693647 1.10040452 1.11111111]]


In [56]:
#eigen vector
eigen_value,eigen_vector=np.linalg.eig(cov_mat)

In [57]:
print(f"eigen value= {eigen_value}\n eigen vector= {eigen_vector}")

eigen value= [3.16639472 0.15876122 0.00817739]
 eigen vector= [[ 0.56323258  0.81917722 -0.10824851]
 [ 0.58134949 -0.48594851 -0.65260004]
 [ 0.58719829 -0.30463539  0.74993029]]


In [58]:
#2d
pc=eigen_vector[0:2,:]

In [59]:
pc

array([[ 0.56323258,  0.81917722, -0.10824851],
       [ 0.58134949, -0.48594851, -0.65260004]])

In [60]:
t=np.array([[1,2],[2,3]])
tt=np.array([[1,2]])
np.dot(t,tt.T)

array([[5],
       [8]])

In [61]:
updated_dataset=np.dot(dataset,pc.T)

In [62]:
updated_dataset

array([[-2.25347422e+00,  9.45547698e-01],
       [-1.59635280e+00,  7.22873886e-01],
       [-1.31473678e+00,  1.03016851e+00],
       [-1.58562458e-01, -4.17826556e-01],
       [ 3.95680881e-01, -1.87111739e-03],
       [ 6.33492357e-01, -2.05615548e-01],
       [ 9.75428699e-01,  1.47319502e-01],
       [ 5.88919298e-01, -9.68241504e-01],
       [ 9.99242908e-01, -5.44719444e-01],
       [ 1.73036211e+00, -7.07635430e-01]])