In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

file=open(r'Fish_PCA.csv')
docs=file.read().split('\n')
docs=docs[1:-1]
ds=list()
for i in docs:
  t=list()
  temp=i.split(',')
  for j in temp:
    try:
      t.append(eval(j))
    except:
      continue
  ds.append(t)
ds=np.array(ds)

In [ ]:
dataset=ds[0:10,0:3]
print(dataset)

[[242.   23.2  25.4]
 [290.   24.   26.3]
 [340.   23.9  26.5]
 [363.   26.3  29. ]
 [430.   26.5  29. ]
 [450.   26.8  29.7]
 [500.   26.8  29.7]
 [390.   27.6  30. ]
 [450.   27.6  30. ]
 [500.   28.5  30.7]]


In [ ]:
#mean centricity
scaler=StandardScaler()
dataset=scaler.fit_transform(dataset)
print(dataset)

[[-1.86378525 -1.71185197 -1.83448714]
 [-1.28097292 -1.24285143 -1.32332973]
 [-0.67387675 -1.3014765  -1.2097392 ]
 [-0.39461251  0.10552512  0.21014249]
 [ 0.41889636  0.22277526  0.21014249]
 [ 0.66173483  0.39865046  0.60770936]
 [ 1.268831    0.39865046  0.60770936]
 [-0.06678058  0.867651    0.77809516]
 [ 0.66173483  0.867651    0.77809516]
 [ 1.268831    1.39527661  1.17566203]]


In [ ]:
#covariance matrix
cov_mat=np.cov([dataset[:,0],dataset[:,1],dataset[:,2]])
print(cov_mat)

[[1.11111111 0.9741667  1.00693647]
 [0.9741667  1.11111111 1.10040452]
 [1.00693647 1.10040452 1.11111111]]


In [ ]:
#eigen vector
eigen_value,eigen_vector=np.linalg.eig(cov_mat)

In [ ]:
print(f"eigen value= {eigen_value}\n eigen vector= {eigen_vector}")

eigen value= [3.16639472 0.15876122 0.00817739]
 eigen vector= [[ 0.56323258  0.81917722 -0.10824851]
 [ 0.58134949 -0.48594851 -0.65260004]
 [ 0.58719829 -0.30463539  0.74993029]]


In [ ]:
#2d
pc=eigen_vector[0:2,:]

In [ ]:
pc

array([[ 0.56323258,  0.81917722, -0.10824851],
       [ 0.58134949, -0.48594851, -0.65260004]])

In [ ]:
t=np.array([[1,2],[2,3]])
tt=np.array([[1,2]])
np.dot(t,tt.T)

array([[5],
       [8]])

In [ ]:
updated_dataset=np.dot(dataset,pc.T)

In [ ]:
updated_dataset

array([[-2.25347422e+00,  9.45547698e-01],
       [-1.59635280e+00,  7.22873886e-01],
       [-1.31473678e+00,  1.03016851e+00],
       [-1.58562458e-01, -4.17826556e-01],
       [ 3.95680881e-01, -1.87111739e-03],
       [ 6.33492357e-01, -2.05615548e-01],
       [ 9.75428699e-01,  1.47319502e-01],
       [ 5.88919298e-01, -9.68241504e-01],
       [ 9.99242908e-01, -5.44719444e-01],
       [ 1.73036211e+00, -7.07635430e-01]])

In [1]:
#campusX

In [11]:
import numpy as np
import pandas as pd

np.random.seed(23)

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = df.append(df1,ignore_index=True)

df = df.sample(40)

<ipython-input-11-459eff829b6b>:21: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.



In [12]:
df.head()

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [13]:

import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [14]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [15]:

# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [16]:
# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [17]:

eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [18]:
eigen_vectors


array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [20]:

pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [21]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0
2 -0.271876  0.498222       1
3 -0.621586  0.023110       1
4  1.567286  1.730967       1

In [22]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()